### ISSUE TITLE
Any chance you make available pre-built binaries?

### ISSUE THREAD

**Issue by mkanet** [bmsimons/huecli#2]
Hi Bart,

Thank you for making this possible.  I've been desperately looking for a way to control my Hue lights via Windows Command-line.  However, I don't have a development environment to build the binaries for huecli.

I was hoping you wouldn't mind sharing pre-built binaries for the Windows platform.  I would really appreciate it.

Thanks,
Michael

**Comment by andyreload** [comment]
> 
> 
> Hi Bart,
> 
> Thank you for making this possible. I've been desperately looking for a way to control my Hue lights via Windows Command-line. However, I don't have a development environment to build the binaries for huecli.
> 
> I was hoping you wouldn't mind sharing pre-built binaries for the Windows platform. I would really appreciate it.
> 
> Thanks,
> Michael

Hey pal , download DOT.net core SDK 
[https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.302-windows-x64-installer](url)

Install it , then run  at the command prompt . inside huecli-master folder 
**dotnet restore** 

After this compile with this command 
**dotnet build -c Release -r win-x64**

If successful , huecli.exe will be inside the bin folder ,created from the compiler

**Comment by mkanet** [comment]
Thank you.
